
version: "3.9"
services:
  backend:
    image: ghcr.io/chof747/storagemanager_backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ${BACKEND_DB_PATH}:/data/db.db
    environment:
      - DATABASE_URL=sqlite:////data/db.db

  frontend:
    image: ghcr.io/chof747/storagemanager_frontend:latest
    ports:
      - "1850:3000"
