
version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ${BACKEND_DB_PATH}:/data/db.db
    environment:
      - DATABASE_URL=sqlite:////data/db.db

  frontend:
    build:
      context: ./frontend
    ports:
      - "1850:3000"
