services:
  backend:
    image: ghcr.io/chof747/storagemanager_backend:test
    ports:
      - "8000:8000"
    volumes:
      - ./data/backend/:/data
    environment:
      - DATABASE_URL=sqlite:////data/test.db 
      - PRINT_STRATEGIES_PATH=/data/print-strategies
    networks:
      storage_manager:
        aliases:
          - storeman_backend


  frontend:
    image: ghcr.io/chof747/storagemanager_frontend:test
    volumes:
      - ./frontend/.env:/app/.env
      - ./frontend/public/config.json:/usr/share/nginx/html/config.json
    ports:
      - "3010:80"
    env_file:
      - ./frontend/.env
    networks:
      storage_manager:
        aliases:
          - storeman_frontend
networks:
  storage_manager:
