services:
  backend:
    build:
      context: ./backend
    image: storagemanager_backend:local
    ports:
      - "8000:8000"
    volumes:
      - ./data/backend/:/data
    environment:
      - DATABASE_URL=postgresql+psycopg://pgdev_user:pgdev_pass@host.docker.internal:5432/postgres
      - DB_SCHEMA=storage_management_uat
      - PRINT_STRATEGIES_PATH=/data/print-strategies
      - PARTSBOX_BASE_URL=https://partsbox.com/api/1
      - PARTSBOX_API_KEY=partsboxapi_4k3kzyt54ak8c8vd15d32r2aq7cb4171d88aace8dbd6715acc8b41fab188755d
      - PARTSBOX_CACHE_EXPIRATION=1800
    networks:
      storage_manager:
        aliases:
          - storeman_backend

  frontend:
    build:
      context: ./frontend
    image: storagemanager_frontend:local
    volumes:
      - ./frontend/.env:/app/.env
      - ./frontend/public/config.json:/usr/share/nginx/html/config.json
    ports:
      - "3010:80"
    env_file:
      - ./frontend/.env
    networks:
      storage_manager:
        aliases:
          - storeman_frontend
networks:
  storage_manager:
