"""hardware_list_reorder

Revision ID: 0e4e5b0b58e8
Revises: ac86aef280b5
Create Date: 2025-04-13 22:46:33.819320

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e4e5b0b58e8"
down_revision: Union[str, None] = "ac86aef280b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hardware_items",
        sa.Column("reorder", sa.BOOLEAN(), default=False, nullable=True),
    )
    op.add_column(
        "hardware_items", sa.Column("reorder_link", sa.VARCHAR, nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hardware_items", "reorder")
    op.drop_column("hardware_items", "reorder_link")
    # ### end Alembic commands ###
