"""added_label_queue

Revision ID: 26d7391fbb47
Revises: 763c6d8c4452
Create Date: 2025-04-18 21:47:45.670199

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26d7391fbb47"
down_revision: Union[str, None] = "763c6d8c4452"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hardware_items",
        sa.Column(
            "queued_for_printing", sa.Boolean(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hardware_items", "queued_for_printing")
    # ### end Alembic commands ###
