"""added label and description to hwitem

Revision ID: 8646c84fc4ef
Revises: b049b2c878ef
Create Date: 2025-07-06 08:01:13.026509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8646c84fc4ef'
down_revision: Union[str, None] = 'b049b2c878ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hardware_items', sa.Column('label', sa.String(), nullable=True))
    op.add_column('hardware_items', sa.Column('detailed_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hardware_items', 'detailed_description')
    op.drop_column('hardware_items', 'label')
    # ### end Alembic commands ###
