"""strateg_nullable

Revision ID: b049b2c878ef
Revises: 34229333d949
Create Date: 2025-05-27 18:57:23.372207

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b049b2c878ef"
down_revision: Union[str, None] = "34229333d949"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("storage_type", schema=None) as batch_op:
        batch_op.alter_column("printing_strategy", nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("storage_type", schema=None) as batch_op:
        batch_op.alter_column("printing_strategy", nullable=False)
    # ### end Alembic commands ###
