name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  determine-build-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - name: Compute tag
        id: set-tag
        run: |
          BRANCH="${{ github.ref_name }}"
          if [[ "$BRANCH" == "main" ]]; then
            TAG="latest"
          elif [[ "$BRANCH" == release/* ]]; then
            TAG="test"
          else
            echo "Unsupported branch: $BRANCH"
            exit 1
          fi
          echo "TAG=$TAG"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

  build-and-push-backend:
    runs-on: ubuntu-latest
    needs: determine-build-tag
    permissions:
      contents: read
      packages: write

    steps:
      - name: Decide tag
        id: tag
        run: |
          if [[ "$BRANCH_NAME" == "main" ]]; then
            TAG=latest
          elif [[ "$BRANCH_NAME" == release/* ]]; then
            TAG=test
          else
            echo "Invalid branch"
            exit 1
          fi
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/storagemanager_backend:${{ needs.determine-build-tag.outputs.tag }}

  build-and-push-frontend:
    runs-on: ubuntu-latest
    needs: determine-build-tag
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/storagemanager_frontend:${{ needs.determine-build-tag.outputs.tag }}
