name: Run Python Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # change if needed

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install pdm
          pdm install -G dev

      - name: Create .env file
        run: echo "APITEST_DATABASE_PATH=data/backend/api_test.db" > ./backend/.env

      - name: Run tests
        working-directory: backend
        run: pdm run pytest
